import { buildCsv, downloadCsv } from "@/lib/csv";

export type ExportRow = Record<string, string | number | boolean | null | undefined>;

function safeText(value: unknown): string {
  if (value === null || value === undefined) return "";
  return String(value);
}

function prettifyHeader(key: string): string {
  return key
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

export function exportRowsAsCsv(filename: string, rows: ExportRow[]) {
  if (!rows.length) return;
  const headers = Array.from(
    rows.reduce((set, row) => {
      Object.keys(row).forEach((key) => set.add(key));
      return set;
    }, new Set<string>()),
  );
  const tableRows = rows.map((row) => headers.map((header) => row[header] ?? ""));
  const csvHeaders = headers.map(prettifyHeader);
  downloadCsv(filename, buildCsv(csvHeaders, tableRows));
}

export async function exportRowsAsExcel(filename: string, rows: ExportRow[]) {
  if (!rows.length) return;
  const XLSX = await import("xlsx");
  const sheet = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Report");
  XLSX.writeFile(wb, filename);
}

export async function exportMultiSheetExcel(
  filename: string,
  sheets: { name: string; rows: ExportRow[] }[],
) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  let added = 0;
  for (const { name, rows } of sheets) {
    if (!rows.length) continue;
    const safeName = name.replace(/[\\/?*[\]]/g, "").slice(0, 31);
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), safeName || `Sheet${added + 1}`);
    added += 1;
  }
  if (!added) return;
  XLSX.writeFile(wb, filename);
}

export type PdfExportOptions = {
  generatedBy?: string | null;
  generatedAt?: string;
  dateRange?: string;
  summary?: string;
  logoDataUrl?: string | null;
};

export async function exportRowsAsPdf(
  title: string,
  filename: string,
  rows: ExportRow[],
  options?: PdfExportOptions,
) {
  if (!rows.length) return;
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const headers = Array.from(
    rows.reduce((set, row) => {
      Object.keys(row).forEach((key) => set.add(key));
      return set;
    }, new Set<string>()),
  );
  const pdf = new jsPDF({ orientation: "landscape" });
  let y = 14;
  if (options?.logoDataUrl) {
    try {
      pdf.addImage(options.logoDataUrl, "PNG", 14, 8, 18, 18);
      y = 28;
    } catch {
      /* ignore invalid logo */
    }
  }
  pdf.setFontSize(14);
  pdf.text(title, options?.logoDataUrl ? 36 : 14, y);
  y += 6;
  pdf.setFontSize(9);
  const metaLines = [
    options?.generatedAt ? `Generated: ${options.generatedAt}` : null,
    options?.generatedBy ? `Generated by: ${options.generatedBy}` : null,
    options?.dateRange ? `Range: ${options.dateRange}` : null,
    options?.summary ? `Summary: ${options.summary}` : null,
  ].filter(Boolean) as string[];
  metaLines.forEach((line) => {
    pdf.text(line, 14, y);
    y += 5;
  });
  autoTable(pdf, {
    head: [headers.map(prettifyHeader)],
    body: rows.map((row) => headers.map((header) => safeText(row[header]))),
    startY: Math.max(22, y + 2),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [201, 162, 39] },
  });
  pdf.save(filename);
}
