import { exportRowsAsCsv, exportRowsAsExcel, exportRowsAsPdf, type ExportRow } from "@/components/reports/reportsExport";

export type ReportExportMeta = {
  companyName: string;
  reportName: string;
  generatedAt: string;
  generatedBy: string | null;
  dateFrom: string;
  dateTo: string;
  summary?: string;
  logoDataUrl?: string | null;
};

function metaRows(meta: ReportExportMeta): ExportRow[] {
  return [
    { field: "Company", value: meta.companyName },
    { field: "Report", value: meta.reportName },
    { field: "Generated date", value: meta.generatedAt },
    { field: "Generated by", value: meta.generatedBy || "—" },
    { field: "Date from", value: meta.dateFrom },
    { field: "Date to", value: meta.dateTo },
    { field: "Summary", value: meta.summary || "" },
  ];
}

export async function exportReportWithMeta(
  format: "pdf" | "excel" | "csv",
  filenameBase: string,
  dataRows: ExportRow[],
  meta: ReportExportMeta,
) {
  const rows = [...metaRows(meta), { field: "—", value: "—" }, ...dataRows];
  if (format === "csv") {
    exportRowsAsCsv(`${filenameBase}.csv`, rows);
    return;
  }
  if (format === "excel") {
    await exportRowsAsExcel(`${filenameBase}.xlsx`, rows);
    return;
  }
  await exportRowsAsPdf(
    `${meta.companyName} — ${meta.reportName}`,
    `${filenameBase}.pdf`,
    rows,
    {
      generatedBy: meta.generatedBy,
      generatedAt: meta.generatedAt,
      dateRange: `${meta.dateFrom} → ${meta.dateTo}`,
      summary: meta.summary,
      logoDataUrl: meta.logoDataUrl,
    },
  );
}
